[workspace]
members = ["measure"]
resolver = "2"

[workspace.dependencies]
clap = { version = "4.4.7", features = ["derive"] }
color-eyre = "0.6.2"
itertools = "0.11.0"
rayon = "1.8.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
