[package]
name = "measure"
version = "0.1.0"
edition = "2021"

[dependencies]
clap.workspace = true
color-eyre.workspace = true
itertools.workspace = true
rayon.workspace = true
serde_json.workspace = true
serde.workspace = true
