[package]
name = "measure"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true, features = ["derive"] }
color-eyre.workspace = true
itertools.workspace = true
rayon.workspace = true
